### ISSUE TITLE
AttributeError: 'RenderSettings' object has no attribute 'tile_x'

### ISSUE THREAD

**Issue by hungminhsu** [OpenMotionLab/MotionGPT#56]
AttributeError: 'RenderSettings' object has no attribute 'tile_x'
I got errors when trying to render SMPL meshes for visualization.

**Comment by longquan0609** [comment]
blend target is 2.93,  It caused by higher version such as v4.0...

**Comment by Run542968** [comment]
I find the isse is solved by authors. You can see [here](https://github.com/OpenMotionLab/MotionGPT/blob/a56b09ff7d20b4ddde9c0080aeb4a6b237f031c3/mGPT/render/blender/scene.py#L26). This  code works in my device (Blender 4.1).

**Comment by Run542968** [comment]
I find the isse is solved by authors. You can see [here](https://github.com/OpenMotionLab/MotionGPT/blob/a56b09ff7d20b4ddde9c0080aeb4a6b237f031c3/mGPT/render/blender/scene.py#L26-L33). This code works in my device (Blender 4.1).
